// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiYAl70ae7FssoaoV30FYzyL4_s5XRACM',
    appId: '1:951094222896:web:abc5942fd90020237c0df5',
    messagingSenderId: '951094222896',
    projectId: 'covidz-73273',
    authDomain: 'covidz-73273.firebaseapp.com',
    storageBucket: 'covidz-73273.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiYAl70ae7FssoaoV30FYzyL4_s5XRACM',
    appId: '1:951094222896:web:2b7b380265397ff57c0df5',
    messagingSenderId: '951094222896',
    projectId: 'covidz-73273',
    authDomain: 'covidz-73273.firebaseapp.com',
    storageBucket: 'covidz-73273.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCiYAl70ae7FssoaoV30FYzyL4_s5XRACM',
    appId: '1:951094222896:web:520280d52bf0f7317c0df5',
    messagingSenderId: '951094222896',
    projectId: 'covidz-73273',
    authDomain: 'covidz-73273.firebaseapp.com',
    storageBucket: 'covidz-73273.appspot.com',
  );
}
